# This file is generated by running "yarn install" inside your project.
# It is essentially a version of yarn.lock that Nix can better understand
# Manual changes WILL be lost - proceed with caution!
let
  packages = {
    "bson@npm:6.10.1" = {
      name = "bson";
      reference = "npm:6.10.1";
      linkType = "HARD";
      outputName = "bson-6.10.1-ce7e3d7ed8";
      outputHash = "89f0ee7a45211648afa5a32d7f4d7ce436e20614b7c5d37c9fd6bc6e9464eec0ddeab8432a836d819bef1f4896256d874044603cf5f4b2123c00734842799601";
      flatName = "bson";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:6.10.1";
      checksum = "10c0/89f0ee7a45211648afa5a32d7f4d7ce436e20614b7c5d37c9fd6bc6e9464eec0ddeab8432a836d819bef1f4896256d874044603cf5f4b2123c00734842799601";
    };
    "bson@patch:bson@npm%3A6.10.1#~/.yarn/patches/bson-npm-6.10.1-ce7e3d7ed8.patch::version=6.10.1&hash=5415a2" = {
      name = "bson";
      reference = "patch:bson@npm%3A6.10.1#~/.yarn/patches/bson-npm-6.10.1-ce7e3d7ed8.patch::version=6.10.1&hash=5415a2";
      linkType = "HARD";
      outputName = "bson-6.10.1-57604a837f";
      outputHash = "304561ab6e32a26a2220015870f43fdc885878e88eb3a8be83af721bedcf5fefc2314b4433363818ef5d062b72dd9a2e6502a67abec752d36017cd122e49a97d";
      src = ./.yarn/patches/bson-npm-6.10.1-ce7e3d7ed8.patch;
      shouldBeUnplugged = true;
      flatName = "bson";
      languageName = "node";
      scope = null;
      descriptorRange = "patch:bson@npm%3A6.10.1#~/.yarn/patches/bson-npm-6.10.1-ce7e3d7ed8.patch";
      checksum = "10c0/304561ab6e32a26a2220015870f43fdc885878e88eb3a8be83af721bedcf5fefc2314b4433363818ef5d062b72dd9a2e6502a67abec752d36017cd122e49a97d";
    };
    "one@workspace:packages/one" = {
      name = "one";
      reference = "workspace:packages/one";
      linkType = "SOFT";
      outputName = "one-0.0.0-7b7dd48475";
      src = ./packages/one;
      shouldBeUnplugged = true;
      flatName = "one";
      languageName = "unknown";
      scope = null;
      descriptorRange = "workspace:packages/one";
      dependencies = {
        "bson" = packages."bson@patch:bson@npm%3A6.10.1#~/.yarn/patches/bson-npm-6.10.1-ce7e3d7ed8.patch::version=6.10.1&hash=5415a2";
      };
    };
    "patch@workspace:." = {
      name = "patch";
      reference = "workspace:.";
      linkType = "SOFT";
      outputName = "patch-0.0.0-b323ce42d7";
      src = ./.;
      shouldBeUnplugged = true;
      flatName = "patch";
      languageName = "unknown";
      scope = null;
      descriptorRange = "workspace:.";
    };
    "three@workspace:packages/three" = {
      name = "three";
      reference = "workspace:packages/three";
      linkType = "SOFT";
      outputName = "three-0.0.0-e5a36279c1";
      src = ./packages/three;
      shouldBeUnplugged = true;
      flatName = "three";
      languageName = "unknown";
      scope = null;
      descriptorRange = "workspace:packages/three";
      bin = {
        "three" = "./index.js";
      };
      dependencies = {
        "one" = packages."one@workspace:packages/one";
        "two" = packages."two@workspace:packages/two";
      };
    };
    "two@workspace:packages/two" = {
      name = "two";
      reference = "workspace:packages/two";
      linkType = "SOFT";
      outputName = "two-0.0.0-f068134a55";
      src = ./packages/two;
      shouldBeUnplugged = true;
      flatName = "two";
      languageName = "unknown";
      scope = null;
      descriptorRange = "workspace:packages/two";
      dependencies = {
        "bson" = packages."bson@patch:bson@npm%3A6.10.1#~/.yarn/patches/bson-npm-6.10.1-ce7e3d7ed8.patch::version=6.10.1&hash=5415a2";
      };
    };
  };
in
packages
